- name: Install common packages
  apt:
    name:
      - htop
      - nano
      - vim-tiny
      - git
      - logrotate
    state: present
    update_cache: yes

- name: Copy metrics.sh to local host with encrypted variables
  template:
    src: metrics.sh.j2
    dest: /metrics.sh
    mode: '0755'

- name: Debug - Show metrics.sh exists
  stat:
    path: /metrics.sh
  register: metrics_file

- name: Debug - Output metrics file status
  debug:
    var: metrics_file

- name: Create initial ansible pull log file
  file:
    path: "/var/log/ansible-pull.log"
    state: touch
    mode: '0644'
  changed_when: false

- name: Copy logrotate configuration for ansible-pull logs
  copy:
    src: ansible-pull-logrotate
    dest: /etc/logrotate.d/ansible-pull
    owner: root
    group: root
    mode: '0644'
